version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
      - JWT_PRIVATE_KEY=lucas1409
      - MONGODB_URI=mongodb://mongodb:27017/userdb
    depends_on:
      - mongodb
    
  mongodb:
    image: mongo:4.0-xenial
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: